server:
  port: 9011
spring:
  application:
    name: bank_operating
  redis:
    host: localhost
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root